version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: docutils
    versions:
    - "0.17"
  - dependency-name: python-dotenv
    versions:
    - 0.16.0
  - dependency-name: setuptools
    versions:
    - 54.1.2
    - 54.2.0
  - dependency-name: virtualenv
    versions:
    - 20.4.3
  - dependency-name: alembic
    versions:
    - 1.5.6
