"""empty message

Revision ID: 82890eac85b7
Revises: 
Create Date: 2020-05-09 11:01:13.914711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82890eac85b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paladins_players',
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('player_platform', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('smite_players',
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('player_platform', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smite_players')
    op.drop_table('paladins_players')
    # ### end Alembic commands ###
