"""empty message

Revision ID: 299c8e2b363c
Revises: 
Create Date: 2019-11-18 09:20:51.448522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299c8e2b363c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champ_alibity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('damage_type', sa.String(length=10), nullable=True),
    sa.Column('recharge_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('champ_skin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_2', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('champion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('weekly_rotation', sa.Boolean(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('lore', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paladins_player',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=4), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smite_player',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=4), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smite_player')
    op.drop_table('session')
    op.drop_table('paladins_player')
    op.drop_table('champion')
    op.drop_table('champ_skin')
    op.drop_table('champ_alibity')
    # ### end Alembic commands ###
