"""empty message

Revision ID: 380f8f7917cd
Revises: 
Create Date: 2019-05-02 23:03:38.975436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380f8f7917cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'players', ['player_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    # ### end Alembic commands ###
