"""empty message

Revision ID: 9b5c994f12a3
Revises: 
Create Date: 2019-11-17 22:36:57.463774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5c994f12a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_model',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('index')
    )
    op.create_table('paladins_players',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('index')
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('smite_players',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smite_players')
    op.drop_table('session')
    op.drop_table('paladins_players')
    op.drop_table('base_model')
    # ### end Alembic commands ###
